"""add_unique_constraint_to_repository

Revision ID: 8aedb8080d33
Revises: c75a5c1b4372
Create Date: 2026-10-05 11:27:54.253346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aedb8080d33'
down_revision: Union[str, Sequence[str], None] = 'c75a5c1b4372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
